import React, { useState, useContext } from "react";
import { withRouter } from "react-router-dom";

import { db } from "../../firebase";

import Login from "../login/login";

import { UserContext } from "../auth/UserContext";

const RegisterForm = ({ history }) => {
  const { isAuth, setIsAuth } = useContext(UserContext);
  // console.log("login....");

  const initialFields = {
    username: "",
    password: "",
  };
  const [values, setValues] = useState(initialFields);
  const [userId, setUserId] = useState(null);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setValues({
      ...values,
      [name]: value,
    });
  };

  const addUser = async (e) => {
    e.preventDefault();
    let isExistingUser = false;

    const querySnapshot = await db
      .collection("users")
      .where("username", "==", values.username)
      .get();

    querySnapshot.forEach(function (doc) {
      isExistingUser = doc.exists;
      alert(`User name exists!,Try with different user name`);
    });

    if (!isExistingUser) {
      addUserToDB({
        username: values.username,
        password: values.password,
      });
    }
  };

  async function addUserToDB(userObj) {
    const { id } = await db.collection("users").add(userObj);

    // Use the Users Id Generated by Firebase in Context, To use it accross all the components
    setUserId(id);
    setValues(initialFields);
    setIsAuth(() => {
      history.push("/profile");
      return true;
    });
  }

  const handleLogout = () => setIsAuth(!isAuth);

  return (
    <>
      {isAuth ? (
        <>
          <p>Welcome, User</p>
          <button onClick={handleLogout}>Logout</button>
        </>
      ) : (
        <div className="signin__wrapper">
          <div>
            <h5>Register </h5>
            <form autoComplete="off" onSubmit={addUser}>
              <label htmlFor="username">User Name:</label>
              <br />
              <input
                value={values.username}
                name="username"
                onChange={handleInputChange}
                required
              />
              <br />
              <label htmlFor="password">Password:</label>
              <br />
              <input
                type="text"
                value={values.password}
                name="password"
                required
                onChange={handleInputChange}
              />
              <br />
              <br />
              <input type="submit" value="Register" />
            </form>
          </div>
          <Login />
        </div>
      )}
    </>
  );
};

export default withRouter(RegisterForm);
